name: MultiverseSurvival
version: '${project.version}'
main: io.github.yuko1101.multiversesurvival.MultiverseSurvival
api-version: '1.20'
authors: [yuko1101]
description: A several worlds management plugin for survival servers.
website: https://github.com/yuko1101/MultiverseSurvival
depend:
  - Multiverse-Core
